name: restigo
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://example.com"

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0-beta.4

dev_dependencies:
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.28.0
  test_api: ^0.7.8
